function plot_exemplaryMRNADistr_withAndWithoutTransport(diffLenPass, diffLenAct, yAct, yPass, x)

% This function plots two exemplary mRNA distributions 'diffLenAct' 
% ('diffLenPass') based on their diffusion lengths 'diffLenAct' 
% ('diffLenPass'), resembling mRNA with (without) dendritic mRNA transport.
% 'x' contains spatial coordinates corresponding to the distributions.

% initialise figure
figure('FileName', [char(datetime('today', 'Format', 'yyyy_MM_dd')), '_exemplaryMRNADistr_withAndWithoutTransport'], ...
       'Name'    , 'exemplaryMRNADistr_withAndWithoutTransport', ...
       'Units'   , 'centimeter', ...
       'Position', [2, 2, 14, 4]);

% load colors
load('3Reds4Blues4Greens3Greys3Violets.mat');

% create axis
ax = axes('Units'               , 'centimeter', ...
          'Position'            , [8.25, 1, 5, 2], ...
          'Color'               , 'none', ...
          'Box'                 , 'off', ...
          'FontSize'            , 10, ...
          'FontName'            , 'Arial', ...
          'LineWidth'           , 0.5, ...
          'TickDir'             , 'out', ...
          'TickLength'          , [0.02, 0.02], ...
          'TickLabelInterpreter', 'tex', ...
          'XLim'                , [x(1), x(end)], ...
          'XTick'               , 0:50:250, ...
          'YLim'                , [0, max([yPass, yAct])]); hold on;
set(get(gca, 'YAxis'), 'Color', 'none')
set(get(gca, 'XLabel'), 'String'     , 'Dendritic distance [\mum]', ...
                        'Interpreter', 'tex', ...
                        'FontSize'   , 10, ...
                        'FontName'   , 'Arial')
% panel label
text('String'             , 'B', ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 12, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'centimeter', ...
     'Position'           , [-0.5, ax.Position(4) + 0.2], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'bottom'); hold on;
% plot normalized mRNA distribution with 'passive' diffusion length
yDat = yPass;
xDat = x;
plot(xDat, yDat, ...
     'Color'    , colors.LightRed, ...
     'LineWidth', 1.5); hold on;
% plot normalized mRNA distribution with 'active' diffusion length
yDat = yAct;
xDat = x;
plot(xDat, yDat, ...
     'Color'    , colors.DarkRed, ...
     'LineWidth', 1.5); hold on;
% label y-axis
text('String'             , 'mRNA / \mum', ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 10, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'normalized', ...
     'Rotation'           , 90, ...
     'Position'           , [0, 0.5], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'bottom'); hold on;
% legend
text('String'             , 'Diffusion length', ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 10, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'normalized', ...
     'Position'           , [0.7, 0.6], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'bottom'); hold on;
text('String'             , [num2str(diffLenPass), '\mum '], ...
     'Color'              , colors.LightRed, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 10, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'normalized', ...
     'Position'           , [0.7, 0.6], ...
     'HorizontalAlignment', 'right', ...
     'VerticalAlignment'  , 'top'); hold on;
text('String'             , [num2str(diffLenAct), '\mum '], ...
     'Color'              , colors.DarkRed, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 10, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'normalized', ...
     'Position'           , [0.7, 0.6], ...
     'HorizontalAlignment', 'left', ...
     'VerticalAlignment'  , 'top'); hold on;
 