function plot_experimentalParameterDistributions(sources_m, sourceDat_m, mRNALifes   , ...
                                                 sources_p, sourceDat_p, protLifes   , ...
                                                 sources_a, sourceDat_a, protLengths , ...
                                                 sources_s, sourceDat_s, protPerSpine, ...
                                                 sources_d, sourceDat_d, protDiffConsts)

% set panel labels
panelLabel = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'};
% labels "low", "medium", "high"
lowMedHigh = {'low', 'medium', 'high'};
% load colors
load('3Reds4Blues4Greens3Greys3Violets.mat');
% small colormaps
RedColors  = {colors.LightRed, colors.Red, colors.DarkRed};
BlueColors = {colors.LightBlue, colors.Blue, colors.DarkBlue};
% initialise figure
figure('FileName', [char(datetime('today', 'Format', 'yyyy_MM_dd')), '_modelParameter'], ...
       'Name'    , 'modelParameter', ...
       'Units'   , 'centimeter', ...
       'Position', [2, 2, 16, 8]);

%% plot protein lifetimes

% axis
ax = axes('Units'               , 'centimeter', ...
          'Position'            , [0.5, 3.5, 3.5, size(sources_p, 1)*0.75], ...
          'Color'               , 'none', ...
          'Box'                 , 'off', ...
          'View'                , [90, -90], ...
          'FontSize'            , 10, ...
          'FontName'            , 'Arial', ...
          'LineWidth'           , 0.5, ...
          'TickDir'             , 'out', ...
          'TickLength'          , [0.02, 0.02], ...
          'TickLabelInterpreter', 'tex', ...
          'XLim'                , [0.4, length(sources_p) + 0.5], ...
          'XTick'               , 1:length(sources_p), ...
          'XTickLabel'          , sources_p(:, 1), ...
          'YLim'                , [-0.5, 2], ...
          'YTick'               , 0:2, ...
          'YTickLabel'          , {'1', '10', '100'}, ...
          'YTickLabelRotation'  , 0); hold on;
set(get(gca, 'XAxis'), 'Color', 'none')
set(get(gca, 'YLabel'), 'String'     , 'Protein half-life [d]', ...
                        'Interpreter', 'tex', ...
                        'FontSize'   , 10, ...
                        'FontName'   , 'Arial')
% panel label
text('String'             , panelLabel{1}, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 12, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'centimeter', ...
     'Position'           , [0, ax.Position(4) - 0.1], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'bottom'); hold on;
% plot data distributions per source with quartiles in white on top and
% label on the right
for i = 1:size(sources_p, 1)
    % plot data distributions
    xDat    = i.*ones(numel(sourceDat_p{i}), 1);
    yDat    = log10(sourceDat_p{i});
    if strcmp(sources_p{i, 2}, 'in vitro')
        col = colors.LightBlue;
    elseif strcmp(sources_p{i, 2}, 'in vivo')
        col = colors.Blue;
    end
    swarmchart(xDat, yDat, ...
               'SizeData'       , 3, ...
               'MarkerFaceColor', col, ...
               'MarkerFaceAlpha', 1, ...
               'MarkerEdgeColor', 'none'); hold on;
    % data source
    text('String'             , sources_p{i}, ...
         'Interpreter'        , 'tex', ...
         'FontSize'           , 10, ... 
         'FontName'           , 'Arial', ...
         'Units'              , 'normalized', ...
         'Position'           , [1.05, (i - 0.4)/(0.1 + size(sources_p, 1))], ...
         'HorizontalAlignment', 'left', ...
         'VerticalAlignment'  , 'middle'); hold on;
end
% plot the values for "small", "medium", and "high" protein lifetimes
for i = 1:numel(protLifes)
    xDat = 0.4;
    yDat = log10(protLifes(i));
    scatter(xDat, yDat, ...
            'SizeData'       , 15, ...
            'LineWidth'      , 0.5, ...
            'MArker'         , 'd', ...
            'MarkerFaceColor', BlueColors{i}, ...
            'MarkerFaceAlpha', 1, ...
            'MarkerEdgeColor', 'black'); hold on;
end
% label "in vitro" and "in vivo" data
text('String'             , 'in vitro', ...
     'Color'              , colors.LightBlue, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 10, ...
     'FontName'           , 'Arial', ...
     'Rotation'           , 90, ...
     'Units'              , 'normalized', ...
     'Position'           , [0, (1.5 - 0.4)/(0.1 + size(sources_p, 1))], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'bottom'); hold on;
text('String'             , 'in vivo', ...
     'Color'              , colors.Blue, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 10, ...
     'FontName'           , 'Arial', ...
     'Rotation'           , 90, ...
     'Units'              , 'normalized', ...
     'Position'           , [0, (4 - 0.4)/(0.1 + size(sources_p, 1))], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'bottom'); hold on;

%% plot protein length

% axis
ax = axes('Units'               , 'centimeter', ...
          'Position'            , [6, 6.5, 3.5, length(sources_a)*0.75], ...
          'Color'               , 'none', ...
          'Box'                 , 'off', ...
          'View'                , [90, -90], ...
          'FontSize'            , 10, ...
          'FontName'            , 'Arial', ...
          'LineWidth'           , 0.5, ...
          'TickDir'             , 'out', ...
          'TickLength'          , [0.02, 0.02], ...
          'TickLabelInterpreter', 'tex', ...
          'XLim'                , [0.4, length(sources_a) + 0.5], ...
          'XTick'               , 1:length(sources_a), ...
          'XTickLabel'          , sources_a(:, 1), ...
          'YLim'                , [1.5, 4], ...
          'YTick'               , 2:4, ...
          'YTickLabel'          , {'10^2', '10^3', '10^4'}, ...
          'YTickLabelRotation'  , 0); hold on;
set(get(gca, 'XAxis'), 'Color', 'none')
set(get(gca, 'YLabel'), 'String'     , 'Amino acids / protein', ...
                        'Interpreter', 'tex', ...
                        'FontSize'   , 10, ...
                        'FontName'   , 'Arial')
% panel label
text('String'             , panelLabel{2}, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 12, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'centimeter', ...
     'Position'           , [0, ax.Position(4) - 0.1], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'bottom'); hold on;
% plot data distributions per source with quartiles in white on top and
% label on the right
for i = 1:size(sources_a, 1)
    % plot data distributions
    xDat    = i.*ones(numel(sourceDat_a{i}), 1);
    yDat    = log10(sourceDat_a{i});
    swarmchart(xDat, yDat, ...
               'SizeData'       , 3, ...
               'MarkerFaceColor', colors.Blue, ...
               'MarkerFaceAlpha', 1, ...
               'MarkerEdgeColor', 'none'); hold on;
    % data source
    text('String'             , sources_a{i}, ...
         'Interpreter'        , 'tex', ...
         'FontSize'           , 10, ...
         'FontName'           , 'Arial', ...
         'Units'              , 'normalized', ...
         'Position'           , [1.05, (i - 0.4)/(0.1 + size(sources_a, 1))], ...
         'HorizontalAlignment', 'left', ...
         'VerticalAlignment'  , 'middle'); hold on;
end
% plot the values for "small", "medium", and "high" protein lifetimes
for i = 1:numel(protLengths)
    xDat = 0.4;
    yDat = log10(protLengths(i));
    scatter(xDat, yDat, ...
            'SizeData'       , 15, ...
            'LineWidth'      , 0.5, ...
            'MArker'         , 'd', ...
            'MarkerFaceColor', BlueColors{i}, ...
            'MarkerFaceAlpha', 1, ...
            'MarkerEdgeColor', 'black'); hold on;
end

%% plot protein copies per spine

% axis
ax = axes('Units'               , 'centimeter', ...
          'Position'            , [6, 4, 3.5, size(sources_s, 1)*0.75], ...
          'Color'               , 'none', ...
          'Box'                 , 'off', ...
          'View'                , [90, -90], ...
          'FontSize'            , 10, ...
          'FontName'            , 'Arial', ...
          'LineWidth'           , 0.5, ...
          'TickDir'             , 'out', ...
          'TickLength'          , [0.02, 0.02], ...
          'TickLabelInterpreter', 'tex', ...
          'XLim'                , [0.4, length(sources_s) + 0.5], ...
          'XTick'               , 1:length(sources_s), ...
          'XTickLabel'          , sources_s(:, 1), ...
          'YLim'                , [-1, 6], ...
          'YTick'               , 0:2:6, ...
          'YTickLabel'          , {' 1^{ }', '10^2', '10^4', '10^6'}, ...
          'YTickLabelRotation'  , 0); hold on;
set(get(gca, 'XAxis'), 'Color', 'none')
set(get(gca, 'YLabel'), 'String'     , 'Proteins / spine', ...
                        'Interpreter', 'tex', ...
                        'FontSize'   , 10, ...
                        'FontName'   , 'Arial')
% panel label
text('String'             , panelLabel{3}, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 12, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'centimeter', ...
     'Position'           , [0, ax.Position(4) - 0.1], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'bottom'); hold on;
% plot data distributions per source with quartiles in white on top and
% label on the right
for i = 1:size(sources_s, 1)
    % plot data distributions
    xDat    = i.*ones(numel(sourceDat_s{i}), 1);
    yDat    = log10(sourceDat_s{i});
    swarmchart(xDat, yDat, ...
               'SizeData'       , 15, ...
               'MarkerFaceColor', colors.Blue, ...
               'MarkerFaceAlpha', 1, ...
               'MarkerEdgeColor', 'none'); hold on;
    % data source
    text('String'             , sources_s{i}, ...
         'Interpreter'        , 'tex', ...
         'FontSize'           , 10, ...
         'FontName'           , 'Arial', ...
         'Units'              , 'normalized', ...
         'Position'           , [1.05, (i - 0.4)/(0.1 + size(sources_s, 1))], ...
         'HorizontalAlignment', 'left', ...
         'VerticalAlignment'  , 'middle'); hold on;
end
% plot the values for "small", "medium", and "high" protein lifetimes
for i = 1:numel(protPerSpine)
    xDat = 0.4;
    yDat = log10(protPerSpine(i));
    scatter(xDat, yDat, ...
            'SizeData'       , 15, ...
            'LineWidth'      , 0.5, ...
            'MArker'         , 'd', ...
            'MarkerFaceColor', BlueColors{i}, ...
            'MarkerFaceAlpha', 1, ...
            'MarkerEdgeColor', 'black'); hold on;
end

%% plot protein diffusion coefficients


% axis
ax = axes('Units'               , 'centimeter', ...
          'Position'            , [6, 1.5, 3.5, size(sources_d, 1)*0.75], ...
          'Color'               , 'none', ...
          'Box'                 , 'off', ...
          'View'                , [90, -90], ...
          'FontSize'            , 10, ...
          'FontName'            , 'Arial', ...
          'LineWidth'           , 0.5, ...
          'TickDir'             , 'out', ...
          'TickLength'          , [0.02, 0.02], ...
          'TickLabelInterpreter', 'tex', ...
          'XLim'                , [0.4, 1.5], ...
          'XTick'               , 1, ...
          'YLim'                , [-3.7, 0.5], ...
          'YTick'               , -4:1:0, ...
          'YTickLabel'          , {'10^{-4}', '10^{-3}', '10^{-2}', '10^{-1}', '10^{0}'}, ...
          'YTickLabelRotation'  , 0); hold on;
set(get(gca, 'XAxis'), 'Color', 'none')
set(get(gca, 'YLabel'), 'String'     , 'Protein diff. const. [\mum^2/s]', ...
                        'Interpreter', 'tex', ...
                        'FontSize'   , 10, ...
                        'FontName'   , 'Arial')
% panel label
text('String'             , panelLabel{4}, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 12, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'centimeter', ...
     'Position'           , [0, ax.Position(4) - 0.1], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'bottom'); hold on;
% plot data distributions per source 
for i = 1:size(sources_d, 1)
    % plot data distributions
    xDat    = i.*ones(numel(sourceDat_d{i}), 1);
    yDat    = log10(sourceDat_d{i});
    swarmchart(xDat, yDat, ...
               'SizeData'       , 15, ...
               'MarkerFaceColor', colors.Blue, ...
               'MarkerFaceAlpha', 1, ...
               'MarkerEdgeColor', 'none'); hold on;
    % data source
    text('String'             , sources_d{i}, ...
         'Interpreter'        , 'tex', ...
         'FontSize'           , 10, ...
         'FontName'           , 'Arial', ...
         'Units'              , 'normalized', ...
         'Position'           , [1.05, (i - 0.4)/(0.1 + size(sources_d, 1))], ...
         'HorizontalAlignment', 'left', ...
         'VerticalAlignment'  , 'middle'); hold on;
end
% plot the values for "small", "medium", and "high" protein diffusion
% constants
for i = 1:numel(protDiffConsts)
    xDat = 0.4;
    yDat = log10(protDiffConsts(i));
    scatter(xDat, yDat, ...
            'SizeData'       , 15, ...
            'LineWidth'      , 0.5, ...
            'MArker'         , 'd', ...
            'MarkerFaceColor', BlueColors{i}, ...
            'MarkerFaceAlpha', 1, ...
            'MarkerEdgeColor', 'black'); hold on;
end

%% plot mRNA lifetimes

% axis
ax = axes('Units'               , 'centimeter', ...
          'Position'            , [11, 4, 3.5, 0.25 + size(sources_m, 1)*0.75], ...
          'Color'               , 'none', ...
          'Box'                 , 'off', ...
          'View'                , [90, -90], ...
          'FontSize'            , 10, ...
          'FontName'            , 'Arial', ...
          'LineWidth'           , 0.5, ...
          'TickDir'             , 'out', ...
          'TickLength'          , [0.02, 0.02], ...
          'TickLabelInterpreter', 'tex', ...
          'XLim'                , [0.4, length(sources_m) + 0.5], ...
          'XTick'               , 1:length(sources_m), ...
          'XTickLabel'          , sources_m(:, 1), ...
          'YLim'                , [-0.5, 2], ...
          'YTick'               , 0:2, ...
          'YTickLabel'          , {'1', '10', '100'}, ...
          'YTickLabelRotation'  , 0); hold on;
set(get(gca, 'XAxis'), 'Color', 'none')
set(get(gca, 'YLabel'), 'String'     , 'mRNA half-life [h]', ...
                        'Interpreter', 'tex', ...
                        'FontSize'   , 10, ...
                        'FontName'   , 'Arial')
% panel label
text('String'             , panelLabel{5}, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 12, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'centimeter', ...
     'Position'           , [0, ax.Position(4) - 0.1], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'bottom'); hold on;
% plot data distributions per source with quartiles in white on top and
% label on the right
for i = 1:size(sources_m, 1)
    % plot data distributions
    xDat    = i.*ones(numel(sourceDat_m{i}), 1);
    yDat    = log10(sourceDat_m{i});
    swarmchart(xDat, yDat, ...
               'SizeData'       , 3, ...
               'MarkerFaceColor', colors.Red, ...
               'MarkerFaceAlpha', 1, ...
               'MarkerEdgeColor', 'none'); hold on;
    % data source
    text('String'             , sources_m{i}, ...
         'Interpreter'        , 'tex', ...
         'FontSize'           , 10, ...
         'FontName'           , 'Arial', ...
         'Units'              , 'normalized', ...
         'Position'           , [1.05, (i - 0.4)/(0.1 + size(sources_m, 1))], ...
         'HorizontalAlignment', 'left', ...
         'VerticalAlignment'  , 'middle'); hold on;
end
% plot the values for "small", "medium", and "high" protein lifetimes
for i = 1:numel(mRNALifes)
    xDat = 0.4;
    yDat = log10(mRNALifes(i));
    scatter(xDat, yDat, ...
            'SizeData'       , 15, ...
            'LineWidth'      , 0.5, ...
            'MArker'         , 'd', ...
            'MarkerFaceColor', RedColors{i}, ...
            'MarkerFaceAlpha', 1, ...
            'MarkerEdgeColor', 'black'); hold on;
end

%% plot legend with model parameters

% axis
ax = axes('Units'               , 'centimeter', ...
          'Position'            , [0.15, 0.75, 5.5, 1], ...
          'Color'               , 'none', ...
          'Box'                 , 'off', ...
          'XLim'                , [0, 1], ...
          'YLim'                , [0, 1]); hold on;
set(get(gca, 'XAxis'), 'Color', 'none')
set(get(gca, 'YAxis'), 'Color', 'none')
% markers for "low", "medium", "high" value
markerPos = [0.18, 0.36, 0.665];
for j = 1:3
    xDat = markerPos(j);
    yDat = 0.25;
    scatter(xDat, yDat, ...
            'SizeData'       , 15, ...
            'LineWidth'      , 0.5, ...
            'MArker'         , 'd', ...
            'MarkerFaceColor', 'black', ...
            'MarkerFaceAlpha', 0.2*j, ...
            'MarkerEdgeColor', 'black'); hold on;
    % label dots with protein names
    text('String'             , lowMedHigh{j}, ...
         'Interpreter'        , 'tex', ...
         'FontSize'           , 10, ...
         'FontName'           , 'Arial', ...
         'Units'              , 'data', ...
         'Position'           , [j*0.25, 0.25], ...
         'HorizontalAlignment', 'center', ...
         'VerticalAlignment'  , 'middle'); hold on;
end
% legend title
text('String'             , 'Model parameters', ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 10, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'data', ...
     'Position'           , [0.5, 0.75], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'middle'); hold on;
