function plot_protDiffConstVsMRNAEnrichment(protDiffConstsAvg, mRNAEnrichmentAvg)

% initialise figure
figure('FileName', [char(datetime('today', 'Format', 'yyyy_MM_dd')), '_protDiffConstVsMRNAEnrichment'], ...
       'Name'    , 'protDiffConstVsMRNAEnrichment', ...
       'Units'   , 'centimeter', ...
       'Position', [2, 2, 7, 5]);

% load colors
load('3Reds4Blues4Greens3Greys3Violets.mat');

% axis
ax = axes('Units'               , 'centimeter', ...
          'Position'            , [2, 1.25, 3, 3], ...
          'Color'               , 'none', ...
          'Box'                 , 'off', ...
          'FontSize'            , 10, ...
          'FontName'            , 'Arial', ...
          'LineWidth'           , 0.5, ...
          'TickDir'             , 'out', ...
          'TickLength'          , [0.02, 0.02], ...
          'TickLabelInterpreter', 'tex', ...
          'XLim'                , [-3.5, 0.2], ...
          'YLim'                , [-3.5, 3.5], ...
          'YTick'               , [-3, 0, 3]); hold on;
set(get(gca, 'XLabel'), 'String'     , "log_{10} D_p [\mum^{2}/s]", ...
                        'Interpreter', 'tex', ...
                        'FontSize'   , 10, ...
                        'FontName'   , 'Arial')
set(get(gca, 'YLabel'), 'String'     , {"log_2 mRNA", "neurite:soma"}, ...
                        'Interpreter', 'tex', ...
                        'FontSize'   , 10, ...
                        'FontName'   , 'Arial')
% panel label
text(ax, ...
     'String'             , 'B', ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 12, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'centimeter', ...
     'Position'           , [-1.6, ax.Position(4)], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'bottom'); hold on;    

% ----------------------------------------------------------------------- %

% plot mRNA enrichment vs protein diffusion constant
xDat = log10(protDiffConstsAvg);
yDat = mRNAEnrichmentAvg;
cDat = (yDat >= 0) .* colors.Blue ...
     + (yDat <  0) .* [1, 1, 1];
scatter(ax, xDat, yDat, ...
        'SizeData'       , 15, ...
        'LineWidth'      , 1, ...
        'CData'          , cDat, ...
        'MarkerFaceColor', 'flat', ...
        'MarkerEdgeColor', colors.Blue); hold on;
clear cDat xDat yDat
% plot linear fit
xDat   = log10(protDiffConstsAvg);
yDat   = mRNAEnrichmentAvg;
[P, S] = polyfit(xDat, yDat, 1);
r2     = 1 - (S.normr/norm(yDat - mean(yDat)))^2;
xfit   = [-3.4, 0.1];
yfit   = P(1)*xfit+P(2);
plot(ax, xfit, yfit, ...
     'LineWidth', 0.5, ...
     'LineStyle', '-', ...
     'Color'    , 'black');

% ----------------------------------------------------------------------- %

% legend

% axis
axes('Units'               , 'centimeter', ...
     'Position'            , [5.25, 1.25, 1, 3], ...
     'Color'               , 'none', ...
     'Box'                 , 'off', ...
     'XLim'                , [0, 1], ...
     'YLim'                , [0, 1]); hold on;
set(get(gca, 'XAxis'), 'Color', 'none')
set(get(gca, 'YAxis'), 'Color', 'none')
% legend marker for "dendritic mRNA"
scatter(gca, 0.1, 0.75, ...
        'SizeData'       , 15, ...
        'LineWidth'      , 1, ...
        'CData'          , colors.Blue, ...
        'MarkerFaceColor', 'flat', ...
        'MarkerEdgeColor', 'flat'); hold on;
% label for "dendritic mRNA"
text(gca, ...
     'String'             , {'Neurite-', 'enriched', 'mRNA'}, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 10, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'data', ...
     'Position'           , [0.3, 0.75], ...
     'HorizontalAlignment', 'left', ...
     'VerticalAlignment'  , 'middle'); hold on;
% legend marker for "somatic mRNA" 
scatter(gca, 0.1, 0.25, ...
        'SizeData'       , 15, ...
        'LineWidth'      , 1, ...
        'CData'          , colors.Blue, ...
        'MarkerFaceColor', 'none', ...
        'MarkerEdgeColor', 'flat'); hold on;
% label for "somatic mRNA"
text(gca, ...
     'String'             , {'Somata-', 'enriched', 'mRNA'}, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 10, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'data', ...
     'Position'           , [0.3, 0.25], ...
     'HorizontalAlignment', 'left', ...
     'VerticalAlignment'  , 'middle'); hold on;
