function plot_mRNADiffusionLength(diffLenPass, diffLenAct)

% initialise figure
figure('FileName', [char(datetime('today', 'Format', 'yyyy_MM_dd')), '_mRNADiffusionLength'], ...
       'Name'    , 'mRNADiffusionLength', ...
       'Units'   , 'centimeter', ...
       'Position', [2, 2, 14, 4]);

% load colors
load('3Reds4Blues4Greens3Greys3Violets.mat');

% axis
ax = axes('Units'               , 'centimeter', ...
          'Position'            , [2.25, 1, 5, 2], ...
          'View'                , [90, -90], ...
          'Color'               , 'none', ...
          'Box'                 , 'off', ...
          'FontSize'            , 10, ...
          'FontName'            , 'Arial', ...
          'LineWidth'           , 0.5, ...
          'TickDir'             , 'out', ...
          'TickLength'          , [0.02, 0.02], ...
          'TickLabelInterpreter', 'tex', ...
          'XLim'                , [0.4, 2.5], ...
          'YTickLabelRotation' , 0, ...
          'YLim'                , [0, 120], ...
          'YTick'               , 0:20:120); hold on;
set(get(gca, 'XAxis'), 'Color', 'none')
set(get(gca, 'YLabel'), 'String'     , 'mRNA diffusion length [\mum]', ...
                        'Interpreter', 'tex', ...
                        'FontSize'   , 10, ...
                        'FontName'   , 'Arial')
% panel label
text('String'             , 'A', ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 12, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'centimeter', ...
     'Position'           , [-1.5, ax.Position(4) + 0.2], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'bottom'); hold on;
% plot diffusion length for passive mRNA
yDat = diffLenPass(:);
xDat = ones(size(yDat));
swarmchart(xDat, yDat, ...
         'Marker'          , 'o', ...
         'SizeData'        , 10, ...
         'LineWidth'       , 0.1, ...
         'MarkerFaceColor' , colors.LightRed, ...
         'MarkerEdgeColor' , 'black', ...
         'MarkerEdgeAlpha' , 0.2); hold on;
boxchart(xDat, yDat, ...
         'BoxWidth'        , 0.5, ...
         'MarkerStyle'     , 'none', ...
         'WhiskerLineColor', 'black', ...
         'BoxFaceColor'    , 'black', ...
         'BoxFaceAlpha'    , 0, ...
         'LineWidth'       , 1); hold on;
% label diffusion length for passive mRNA
text('String'             , {'No mRNA', 'transport'}, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 10, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'data', ...
     'Position'           , [1, -0.2], ...
     'HorizontalAlignment', 'right', ...
     'VerticalAlignment'  , 'middle'); hold on;
% plot diffusion length for active mRNA
yDat = diffLenAct(:);
xDat = 2.*ones(size(yDat));
swarmchart(xDat, yDat, ...
         'Marker'          , 'o', ...
         'SizeData'        , 10, ...
         'LineWidth'       , 0.1, ...
         'MarkerFaceColor' , colors.DarkRed, ...
         'MarkerEdgeColor' , 'black', ...
         'MarkerEdgeAlpha' , 0.2); hold on;
boxchart(xDat, yDat, ...
         'BoxWidth'        , 0.5, ...
         'MarkerStyle'     , 'none', ...
         'WhiskerLineColor', 'black', ...
         'BoxFaceColor'    , 'black', ...
         'BoxFaceAlpha'    , 0, ...
         'LineWidth'       , 1); hold on;
% label diffusion length for active mRNA
text('String'             , {'mRNA', 'transport'}, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 10, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'data', ...
     'Position'           , [2, -0.2], ...
     'HorizontalAlignment', 'right', ...
     'VerticalAlignment'  , 'middle'); hold on;
